### ISSUE TITLE
The deck overview screen has a button to create a deck, which directs the user to the deck editing view

### ISSUE THREAD

**Issue by andreas-wiemeyer** [sopra-fs22-group-10/client#24]

**Comment by UlricaK** [comment]
closed by  https://github.com/sopra-fs22-group-10/client/commit/9cc85f5d19f23912c48aeada7a2e2a15534150ed

**Comment by UlricaK** [comment]
closed by https://github.com/sopra-fs22-group-10/client/commit/0f9d484ae594214e1ead30d763e7919e41f97155
